const FETCH_WALLETS_REQUEST = 'FETCH_WALLETS_REQUEST';
const FETCH_WALLETS_SUCCESS = 'FETCH_WALLETS_SUCCESS';
const FETCH_WALLETS_FAILURE = 'FETCH_WALLETS_FAILURE';
const CREATE_WALLET = 'CREATE_WALLET';
const CREATE_WALLET_FAILURE = 'CREATE_WALLET_FAILURE';
const UPDATE_WALLET_FAILURE = 'UPDATE_WALLET_FAILURE';
const DELETE_WALLET_FAILURE = 'DELETE_WALLET_FAILURE';
const DELETE_WALLET = 'DELETE_WALLET';
const UPDATE_WALLET = 'UPDATE_WALLET';
const FETCH_WALLET_REQUEST = 'FETCH_WALLET_REQUEST';
const FETCH_WALLET_SUCCESS = 'FETCH_WALLET_SUCCESS';
const FETCH_WALLET_FAILURE = 'FETCH_WALLET_FAILURE';

export {
  FETCH_WALLETS_REQUEST,
  FETCH_WALLETS_SUCCESS,
  FETCH_WALLETS_FAILURE,
  CREATE_WALLET,
  DELETE_WALLET,
  UPDATE_WALLET,
  CREATE_WALLET_FAILURE,
  UPDATE_WALLET_FAILURE,
  DELETE_WALLET_FAILURE,
  FETCH_WALLET_REQUEST,
  FETCH_WALLET_SUCCESS,
  FETCH_WALLET_FAILURE,
};

